<ColorSelectPopup>
    size_hint: (0.5,0.5)
    title: 'Color Selector'
    BoxLayout:
        id: colorLayout
        #size_hint: (None,None)
        #size: root.width * 0.75, root.height * 0.75
        orientation: 'vertical'

<ShapeSelectPopup>
    size_hint: (0.5,0.5)
    title: 'Shape Selector'
    BoxLayout:
        id: shapeLayout
        #size_hint: (None,None)
        #size: root.width * 0.75, root.height * 0.75
        orientation: 'vertical'
        spacing: self.height * 0.05